#!/usr/bin/env php
<?php

$application = require __DIR__."/bootstrap.php";

$application->make(\JournalMedia\Pharbiter\Console\Kernel::class)
    ->handle(
        new \Symfony\Component\Console\Input\ArgvInput,
        new \Symfony\Component\Console\Output\ConsoleOutput
    );
